name: Swift

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        swift: ["6", "5.10"]
    steps:
    - uses: actions/checkout@v4
    - uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Get Swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
